### ISSUE TITLE
Supply and demand

### ISSUE THREAD

**Issue by mnwato** [SinaMobasheri/TehranSE#1]
Thank you  so much for this helpful package
This will be better if there were all three rows of supply and demand table, I mean:

pd1,pd2,pd3
zd1,zd2,zd3
qd1,qd2,qd3
qo1,qo2,qo3
zo1,zo2,zo3
qo1,qo2,qo3

Thanks in advanced

**Comment by SinaMobasheri** [comment]
I'm glad you found it useful \
and actually there is all three rows of supply and demand ! you can see it in [example](https://gist.github.com/SinaMobasheri/9b35a7abbb0a27c38ea9d215577eec51) \
`getinst()` method return a dictionary, in that dictionary is key called `orders` \
orders is list of three dictionary, first dictionary is first row of supply and demand, second dictionary is... and so on

and the names are the same as you mentioned, but without the numbers because the position of each supply and demand dictionary in list refers to row number
