### ISSUE TITLE
The Day Which TSETMC Structures Had Been Changed

### ISSUE THREAD

**Issue by mnwato** [SinaMobasheri/TehranSE#2]
You work is perfect and ofcourse scraping is a common and good way of gathering data but I want to know your idea about:
The day which "tsetmc" structures had been changed and all of the url that you used to gather data are not working.

**Comment by SinaMobasheri** [comment]
That's a good question
**When the Structure Change**, it's Weakness of Web Scraping \
Personally, I think this will not happen in the near future, even in the next year, because tsetmc is a large site and it will probably cost a lot to restructure the site, also consider that there must be a logical need for restructure the site while this site works well

But let us consider the structure of the site will be changed, how bad it can be ? \
tsetmc is a public site that aims to provide a large amount of information as quickly as possible, so most probably scraper will not be faced with problems such as login page, cookies, csrftoken and complex JavaScript ( as you know, there are solutions for these problems too, but little harder )

**so every time the site structure changes, the package structure also changes, and the package tries to make this information available again.**

**Comment by mnwato** [comment]
Yes, this is the weakness and unfortunatly it takes some time to find a solution. I want to start working with these data for a long term project so this makes me nerves.

I have a question about the way you scrape tsetmc:
You used some url like:
http://www.tsetmc.com/tsev2/data/instinfofast.aspx?i=114312662654155&c=57+

What are these links? and Does these kinds of "tse2/data/..." url depends on the structure of tsetmc.com?
I thinks tsetmc developers can stop these links without changing the structure of "tsetmc". Whats your idea?

Do you know any good web service provider, for the time urls stoped.

**Comment by SinaMobasheri** [comment]
*what are these links?* **These Links Are Hidden API That TSETMC JavaScrip Use**
as you know when you start scraping a website always is good idea to looking at the network activity of site and try to understand structure of site and it's **Hidden API**

*does these kinds of url depends on the structure of tsetmc.com?* **They Are The Structure Of Site**
when i say the **Structure Of Site** i mean that way tsetmc developers build tsetmc, i mean **Backend Of Site** \
but naming are not important at all as you mentioned they can change links but always these links must get inscode of share as url parameter because backend needs that's information so if thay change the link It will not take long to find new link and replace it with olds one because the structure is the same because backend is the same
these 👆🏻 are just theory it's make sense

*whats your idea?*
i think because of the identity of the service that tsetmc offers thay must have logical reasons for any changes

*and about web service provider*
- a while ago tsetmc provide a web service, you see it on this [page](http://cdn.tsetmc.com/Site.aspx?ParTree=11141112) but it seems they not offer web services anymore and you must be non-individual person and then you can use their web service !
- [mabna](https://mabnadp.com/apis) also provide a web service but they are very expensive **20 Million Tomans Per Year !** 

I hope these answers have been useful to you

**Comment by mnwato** [comment]
Thanks for your useful descriptions
